print("print1")
print("print2")
print("print3") 
print("print4 from prateek") 
print("print5") 
print("print6")
print("print7")
print("in the middle")
print("print8")
print("print9")
print("print10")
print("print11") 
adfdasfsdafsadfsa
print("new line ")
WDASDSA
print("my print hello")