print("print1")
print("print2")
print("print3") 
print("print from Prateek") 
print("print5") 
print("print6")
print("print7")
print("print8")
print("This is a new line")
print("print9")
print("print10")
print("last line added")
